version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: vanbora
      POSTGRES_USER: vanbora_user
      POSTGRES_PASSWORD: vanbora_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://vanbora_user:vanbora_pass@db:5432/vanbora

  migrate:
    build: .
    command: bash -c "PYTHONPATH=/app poetry run python src/infra/migrate.py"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://vanbora_user:vanbora_pass@db:5432/vanbora
    volumes:
      - .:/app


volumes:
  postgres_data: 